### ISSUE TITLE
Bot posts multiple times when started

### ISSUE THREAD

**Issue by mattabullock** [mattabullock/Baseball-GDT-Bot#11]
It posts the day before's game as well

**Comment by avery-crudeman** [comment]
As far as I can tell, this only happens when the bot crashes and the compiled files aren't deleted. If you delete them before running the bot it works fine.

**Comment by toddrob99** [comment]
This has never happened for me. The only time it posts duplicate threads is when the bot is restarted after a game ends (but before midnight). And that happens because the teams' records have changed, and the titles therefore don't match what it finds already posted.
