### ISSUE TITLE
Pull requests waiting

### ISSUE THREAD

**Issue by toddrob99** [mattabullock/Baseball-GDT-Bot#29]
I have submitted several pull requests for new features, and I would like to have them considered for merging. They are all optional and default off, except for #22 which sets the suggested sort on pre and post threads in addition to game threads, #23 which adds the leading team code to the score in the scoring decisions section (since it is always in high-low format and not away-home), and #26 which reduces the amount of time after a game ends that the post game thread is posted.

All of these changes have been tested for a full year except for #28 which I just finished last night.

**Comment by mattabullock** [comment]
I'm reviewing these now, gonna close this issue since it's got the same visibility as the open PRs.
