### ISSUE TITLE
Refresh Token

### ISSUE THREAD

**Issue by dgautsch** [mattabullock/Baseball-GDT-Bot#42]
Hi, just need a clarification. In the readme it says "Run the script. Your browser will open. Click allow on the displayed web page."

When I run that the bot simply starts up. I don't have a REFRESH_TOKEN as a result. Am I missing something?

I have PRAW 5.4.0 installed.

EDIT: I grabbed it manually from here: http://praw.readthedocs.io/en/latest/tutorials/refresh_token.html

**Comment by toddrob99** [comment]
You would use setup.py for this. 

I don’t think this repo is working correctly right now though. Please update if you get it working. 

My repo works, and in my repo the setup script is setup_oauth.py. See readme for detailed instructions: https://github.com/toddrob99/Baseball-GDT-Bot.

**Comment by dgautsch** [comment]
Ah right, just noticed this as I saw your post. Thanks for the heads up about this repo.
