### ISSUE TITLE
GDT Line Score issue

### ISSUE THREAD

**Issue by richardpenner** [mattabullock/Baseball-GDT-Bot#45]
The r/TorontoBlueJays sub shows the 2 team names inside the 1st inning column, which also means every subsequent column is off by one. Is this the right place for it? I’ve noticed other subs like the Yankees have differently formatted line  scores and don’t have this issue.

**Comment by toddrob99** [comment]
The game threads in the Blue Jays sub are from u/Fustrate's bot, which is different than this one. The Yankees sub is using my bot (https://github.com/toddrob99/Baseball-GDT-Bot/), which is a fork from this one but I've almost entirely rewritten it. The latest version of my bot is running in r/Phillies, who the Blue Jays just happen to be playing right now. Here's the [r/Phillies game thread](https://www.reddit.com/r/phillies/comments/9a8dcu/game_thread_phillies_6959_blue_jays_5969_sat_aug/) for reference.

**Comment by richardpenner** [comment]
Thanks for the pointer!
